const fs=require('fs'),path=require('path'),http=require('http'),net=require('net'),assert=require('assert'),{spawn}=require('child_process'),Y=require('yaml');
const {makePairs,validateNodes}=require('./chain_model');
const root=path.resolve(__dirname,'..');let hits=[0,0],denied=false;
function socks(port,index){return new Promise(resolve=>{const s=net.createServer(c=>{c.once('data',()=>{c.write(Buffer.from([5,0]));c.once('data',b=>{let host,off;if(b[3]===1){host=[...b.subarray(4,8)].join('.');off=8}else{host=b.subarray(5,5+b[4]).toString();off=5+b[4]}hits[index]++;const r=net.connect(b.readUInt16BE(off),host,()=>{c.write(Buffer.from([5,0,0,1,127,0,0,1,0,0]));c.pipe(r);r.pipe(c)});r.on('error',()=>c.destroy());c.on('close',()=>r.destroy());c.on('error',()=>r.destroy())})})});s.listen(port,'127.0.0.1',()=>resolve(s))})}
async function api(url,b){const r=await fetch('http://127.0.0.1:39242'+url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(b)});return (await r.text()).trim().split('\n').map(JSON.parse).at(-1)}
(async()=>{const web=http.createServer((q,r)=>{r.statusCode=denied&&q.url==='/second'?403:200;r.end('LOCAL FIXTURE ONLY')});await new Promise(r=>web.listen(19980,'127.0.0.1',r));const a=await socks(19981,0),b=await socks(19982,1);try{
const nodes=[{name:'fixture upstream',type:'socks5',server:'127.0.0.1',port:19981},{name:'fixture landing',type:'socks5',server:'127.0.0.1',port:19982}];
assert.throws(()=>validateNodes([nodes[0],nodes[0]]));assert.throws(()=>validateNodes([{...nodes[0],'dialer-proxy':'x'}]));
const sites=['http://127.0.0.1:19980/','http://127.0.0.1:19980/second'];
const first=await api('/api/run',{nodes:Y.stringify({proxies:nodes}),sites,core:'内核/mihomo.exe'});assert(first.done,first.error);assert.equal(first.available.length,2);
const bad=await api('/api/chains',{runId:first.runId,pairs:[{upstream:nodes[0].name,landing:nodes[0].name}]});assert(bad.error);
const pair={upstream:nodes[0].name,landing:nodes[1].name};const before=[...hits];
const second=await api('/api/chains',{runId:first.runId,pairs:[pair],generate:true,yamlName:'LOCAL-FIXTURE-V01'});assert(second.done,second.error);assert.equal(second.report.chain.passed,1);assert(hits[0]>before[0]&&hits[1]>before[1]);
const cfg=Y.parse(fs.readFileSync(second.output,'utf8'));assert.equal(cfg['proxy-groups'].length,8);assert.equal(cfg.proxies[2]['dialer-proxy'],nodes[0].name);
for(const [g,v] of Object.entries({'国内网络':['DIRECT'],'ai 服务':['DIRECT','手动选择','ai 自动选择'],'非中国':['手动选择','ai 自动选择','自动选择'],'漏网之鱼':['手动选择','ai 自动选择','自动选择']}))assert.deepEqual(cfg['proxy-groups'].find(x=>x.name===g).proxies,v);
denied=true;const third=await api('/api/chains',{runId:first.runId,pairs:[pair],generate:false});assert(third.done,third.error);assert.equal(third.report.chain.passed,0);assert.equal(third.output,null);
const fakeResults=Object.fromEntries(nodes.map(n=>[n.name,{sites:{s:{status:200}}}]));for(const type of ['vless','vmess','trojan','ss','hysteria2','tuic','anytls']){const ns=[nodes[0],{...nodes[1],type,password:'LOCAL-FAKE',tls:true,'reality-opts':{'public-key':'LOCAL-FAKE'},'ws-opts':{path:'/local'}}];const c=makePairs(ns,fakeResults,[['s','http://local']], [pair])[0].proxy;const original=structuredClone(c);delete original['dialer-proxy'];original.name=ns[1].name;assert.deepEqual(original,ns[1]);}
const summary={fixture:'LOCAL ONLY, no remote protocol interoperability claim',passed:true,checks:['actual node matrix via two local SOCKS endpoints','actual two-hop traversal counters','two selected sites','403 on second site excludes chain','8 exact groups and memberships','Mihomo -t before root YAML output','generate=false produces no final YAML','self/duplicate/existing dialer rejection','7 protocol field-preserving clones'],hits,rootOutput:second.output};fs.writeFileSync(path.join(root,'VERIFICATION.json'),JSON.stringify(summary,null,2));console.log(JSON.stringify(summary,null,2));
}finally{a.close();b.close();web.close()}})().catch(e=>{console.error(e);process.exitCode=1});
