'use strict';
const $=id=>document.getElementById(id);let available=[],runId=null;
async function jsonResponse(r,label='请求'){const text=await r.text();if(!text.trim())throw Error(label+'返回空响应（HTTP '+r.status+'），请确认面板服务仍在运行');let j;try{j=JSON.parse(text)}catch{throw Error(label+'返回非 JSON（HTTP '+r.status+'）：'+text.slice(0,180))}if(!r.ok)throw Error(j.error||j.message||label+'失败（HTTP '+r.status+'）');return j;}
function invalidate(){runId=null;available=[];$('nodeList').replaceChildren();$('pairs').replaceChildren();$('run').disabled=true;$('addPair').disabled=true;}
function busy(on){for(const id of ['parse','file','nodes','sites','core','refresh','importUrl','importBtn'])$(id).disabled=on;$('run').disabled=on||!runId;$('addPair').disabled=on||!runId||available.length<2;$('exportBtn').disabled=on||!available.length;}
async function importSubscription(){const url=$('importUrl').value.trim();if(!url){$('status').textContent='失败：请输入订阅 URL';return}busy(true);$('status').textContent='正在获取订阅';try{const r=await fetch('/api/import-subscription',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url})});const j=await jsonResponse(r);if(typeof j.text!=='string'||!j.text.trim())throw Error('订阅返回内容为空或格式无效');$('nodes').value=j.text;invalidate();$('status').textContent='订阅已导入当前输入，请点击“解析并测试”；尚未发起节点网络测试';}catch(e){$('status').textContent='失败：'+e.message}finally{busy(false)}}

async function cores(){try{const a=await jsonResponse(await fetch('/api/cores'));if(!Array.isArray(a))throw Error('内核列表响应格式无效');$('core').replaceChildren(...a.map(c=>{const o=new Option(c.id+' — '+c.version,c.id);o.disabled=!c.valid;return o}));const v=a.find(c=>c.valid);if(v)$('core').value=v.id;}catch(e){$('coreInfo').textContent=e.message;}}
async function request(url,data){const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)});if(!r.ok){const text=await r.text();throw Error('请求失败 HTTP '+r.status+(text?'：'+text:''))}if(!r.body)throw Error('任务返回空响应');const reader=r.body.getReader(),decoder=new TextDecoder();let buf='',result;while(true){const {done,value}=await reader.read();if(done)break;buf+=decoder.decode(value,{stream:true});let p;while((p=buf.indexOf('\n'))>=0){const j=JSON.parse(buf.slice(0,p));buf=buf.slice(p+1);if(j.log)$('log').textContent+=j.log;if(j.error)throw Error(j.error);if(j.done)result=j;}}buf+=decoder.decode();if(buf.trim()||!result)throw Error('任务未完整返回，请重新测试');return result;}
function toShareLink(c){const enc=encodeURIComponent;const isIPv6=c.server&&c.server.includes(':')&&!/^\d+$/.test(c.server);const srv=isIPv6?'['+c.server+']':c.server;const name=enc(c.name||'');const q=[];
if(c.sni)q.push('sni='+enc(c.sni));
if(c['skip-cert-verify'])q.push('insecure=1');
if(c.type==='vless'){q.unshift('encryption=none');if(c.network==='ws'){q.push('type=ws','path='+enc(c['ws-opts']?.path||'/'))}else if(c.network==='grpc'){q.push('type=grpc','serviceName='+enc(c['grpc-opts']?.['grpc-service-name']||''))}else if(c.network==='tcp'){q.push('type=tcp')}if(c.flow)q.push('flow='+enc(c.flow));return 'vless://'+c.uuid+'@'+srv+':'+c.port+'?'+q.join('&')+'#'+name}
if(c.type==='vmess'){const j={v:'2',ps:c.name,add:c.server,port:String(c.port),id:c.uuid,aid:String(c.alterId||0),scy:c.cipher||'auto',net:c.network||'tcp',type:'',host:c['ws-opts']?.headers?.Host||'',path:c['ws-opts']?.path||'',tls:c.tls?'tls':'',sni:c.sni||''};return 'vmess://'+btoa(JSON.stringify(j))}
if(c.type==='trojan'){if(c.network==='ws')q.push('type=ws','path='+enc(c['ws-opts']?.path||'/'));return 'trojan://'+enc(c.password||'')+'@'+srv+':'+c.port+'?'+q.join('&')+'#'+name}
if(c.type==='ss'){const b64=btoa((c.cipher||'aes-256-gcm')+':'+(c.password||''));return 'ss://'+b64+'@'+srv+':'+c.port+'#'+name}
if(c.type==='hysteria2'){return 'hysteria2://'+enc(c.password||'')+'@'+srv+':'+c.port+'?'+q.join('&')+'#'+name}
if(c.type==='tuic'){return 'tuic://'+enc(c.uuid||'')+':'+enc(c.password||'')+'@'+srv+':'+c.port+'?'+q.join('&')+'#'+name}
if(c.type==='anytls'){return 'anytls://'+enc(c.password||'')+'@'+srv+':'+c.port+'?'+q.join('&')+'#'+name}
return '# '+c.name+' (unsupported type: '+c.type+')'}
function exportNodes(){const pass=available.filter(n=>n.config);if(!pass.length){$('exportOutput').value='没有通过测试的节点';return}const links=pass.map(n=>toShareLink(n.config)).join('\n');$('exportOutput').value=links;$('status').textContent='已导出 '+pass.length+' 个可用节点(V2RayN格式)';}
function addPair(){const row=document.createElement('div');row.className='pair';for(const [i,cls]of ['up','land'].entries()){const s=document.createElement('select');s.className=cls;s.setAttribute('aria-label',i?'落地':'上游');s.replaceChildren(...available.map(n=>new Option(n.name+' ('+n.type+')',n.name)));s.selectedIndex=i;row.append(s);}const del=document.createElement('button');del.textContent='删除';del.onclick=()=>row.remove();row.append(del);$('pairs').append(row);}
$('parse').textContent='1. 读取并重新测试所有节点';
$('parse').onclick=async()=>{invalidate();busy(true);$('log').textContent='';$('status').textContent='节点实测中';try{const r=await request('/api/run',{nodes:$('nodes').value,core:$('core').value,sites:$('sites').value.split('\n')});runId=r.runId;available=r.available;$('nodeList').replaceChildren(...r.results.map(n=>{const d=document.createElement('div');d.className='node'+(n.passed?' pass':' fail');const lat=Object.entries(n.latency||{}).map(([k,v])=>k.slice(0,12)+': '+(v!=null?v+'ms':'超时')).join(' | ');d.textContent=(n.passed?'✅':'❌')+' '+n.name+' · '+n.type+' · '+lat+(n.exitIp?' · 出口:'+n.exitIp:'');return d;}));$('exportBtn').disabled=available.length===0;$('status').textContent='本轮可配对节点 '+available.length+'；选择配对后执行第二阶段，也可直接导出不含链路的八组配置。';}catch(e){$('status').textContent='失败：'+e.message}finally{busy(false)}};
$('run').onclick=async()=>{busy(true);try{const pairs=[...document.querySelectorAll('.pair')].map(d=>({upstream:d.querySelector('.up').value,landing:d.querySelector('.land').value}));const r=await request('/api/chains',{runId,pairs,yamlName:$('name').value,generate:$('generate').checked});$('status').textContent='完成：链路通过 '+r.report.chain.passed+'/'+pairs.length+'；'+(r.output||'未生成最终 YAML')+'；报告 '+r.dir;}catch(e){$('status').textContent='失败：'+e.message}finally{busy(false)}};
$('file').onchange=async()=>{invalidate();const f=$('file').files[0];if(f)$('nodes').value=await f.text();};for(const id of ['nodes','sites','core'])$(id).addEventListener('input',invalidate);$('refresh').onclick=()=>{invalidate();cores()};$('addPair').onclick=addPair;$('importBtn').onclick=importSubscription;$('exportBtn').onclick=exportNodes;cores();
